name: "Main"
on: [push, pull_request]
jobs:
  package-and-release:
    runs-on: ubuntu-latest
    name: Package and Release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: '**/yarn.lock'
      - run: yarn install --ignore-engines #https://github.com/microsoft/vscode/issues/91009#issuecomment-588410052
      - run: yarn global add vsce
      - run: vsce package
      - name: Get VSIX Name
        id: get-vsix
        run: echo "vsix_name=$(find . -maxdepth 1 -type f -iname "*.vsix" | head -1 | xargs basename)" >> "$GITHUB_OUTPUT"
      # Only run release steps if this is a tag
      - name: Release Extension
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          body: "See [CHANGE LOG](https://github.com/murugaratham/vscode-dotnet-watch/blob/main/CHANGELOG.md) for details."
          artifacts: ${{ steps.get-vsix.outputs.vsix_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Marketplace
        if: startsWith(github.ref, 'refs/tags/v')
        run: vsce publish -p ${{ secrets.MARKETPLACE_TOKEN }}
